vim.keymap.set("n", "<M-h>", "<Plug>(dirbuf_up)", { buffer = true })
vim.keymap.set("n", "<M-l>", "<Plug>(dirbuf_enter)", { buffer = true })
vim.keymap.set("n", "<Left>", "<Plug>(dirbuf_up)", { buffer = true })
vim.keymap.set("n", "<Right>", "<Plug>(dirbuf_enter)", { buffer = true })
vim.keymap.set("n", "<C-j>", "<Plug>(dirbuf_enter)", { buffer = true })
